CREATE DATABASE SoftUni;

USE SoftUni;

CREATE TABLE Towns(
 Id INT PRIMARY KEY IDENTITY,
 [Name] NVARCHAR(150),
)

CREATE TABLE Addresses(
 Id INT PRIMARY KEY IDENTITY,
 AddressText NVARCHAR(150),
 TownId INT FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE Departments (
 Id INT PRIMARY KEY IDENTITY,
 [Name] NVARCHAR(150),
)

CREATE TABLE Employees(
 Id INT PRIMARY KEY IDENTITY,
 FirstName NVARCHAR(50),
 MiddleName NVARCHAR(50),
 LastName NVARCHAR(50),
 JobTitle NVARCHAR(100),
 DepartmentId INT FOREIGN KEY REFERENCES Departments(Id),
 HireDate DATETIME2,
 Salary DECIMAL,
 AddressId INT FOREIGN KEY REFERENCES Addresses(Id) NULL
)